### ISSUE TITLE
As an employee and a manager I want to see information about employee's primary and secondary competences.

### ISSUE THREAD

**Issue by kskowron** [kskowron/skills-mgmt#16]
Competences: programming, doing architecture, testing, managing.
- Primary competence - most recent, currently in use.
- Secondary competence - can be used if necessary, but hasn't been in use for some time or a person has less practice doing it.

Example - primarily @jarekkozak is a manager, but if necessary he can be a programmer.

Subtasks:
- [x] Add Competence class in \common\models\base
- [x] Add Competence class in \common\models
- [x] Add references for primary & secondary competence in Employee class
- [x] Cteate migration for Competence classes (models and models\base)
- [ ] Add fixtures for competences
- [ ] Allow searching employees by primary and secondary competence

**Comment by kskowron** [comment]
@jarekkozak please review the code.

**Comment by jarekkozak** [comment]
From technical point of view looks good but it would be better to have extra table joining Employee and competences instead extending profile (employee). eg.
emplye <- EmployeeRoles -> Competences.
where 
EmployeeRoles
- user_id
- competence_id
- type (primary, secondary, i'd like to be)
  etc...
  Rethink  tabel names Competences....
  R. 
  J.
